services:
  db:
    image: postgres:16
    container_name: xoraq_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: xoraq_redis
    restart: always
    ports:
      - "6379:6379"
    


volumes:
  db_data: